<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GameVersion Condition=" '$(GameVersion)' == '' ">1.6</GameVersion>
    <OutputType>Library</OutputType>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <RootNamespace>RimBridge</RootNamespace>
    <AssemblyName>RimBridge</AssemblyName>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>../$(GameVersion)/Assemblies/</OutputPath>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <NoWarn>CS1591;CS8632</NoWarn>
    <DebugType>portable</DebugType>
    <DefaultItemExcludes>$(DefaultItemExcludes);obj/**;bin/**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="$(GameVersion).*-*" PrivateAssets="All" />
    <PackageReference Include="Lib.Harmony.Ref" Version="2.4.1" PrivateAssets="All" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" PrivateAssets="All" GeneratePathProperty="true" />
  </ItemGroup>

  <Target Name="CopyNewtonsoftJson" AfterTargets="Build">
    <Copy SourceFiles="$(PkgNewtonsoft_Json)\lib\net45\Newtonsoft.Json.dll"
          DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true" />
  </Target>

</Project>
